server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://server:port/community?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username:
    password:

  thymeleaf:
    cache: true

  mail:
    host: smtp.163.com  # smtp.qq.com
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    database: 11
    host: localhost
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.community.entity

community:
  path:
    domain: http://server:8080

aliyun:
  oss:
    file:
      endpoint:
      keyid:
      keysecret:
      bucketname:

